version: '3'

services:
  os:
    image: ubuntu:22.04
    tty: true
    environment:
      - VAR1=abc
      - VAR2=def
    command: /bin/bash -c "apt-get update && apt-get install -y sudo && useradd -m -s /bin/bash usr1 && useradd -m -s /bin/bash usr2 && mkdir -p /Share /Share/pastausr1 /Share/pastausr2 && echo 'olá usr1' > /Share/pastausr1/texto.txt && echo 'olá usr2' > /Share/pastausr2/texto.txt && chown -R usr1:usr1 /Share /home/usr1 && chown -R usr2:usr2 /Share /home/usr2 && tail -f /dev/null"
